window:
  padding: { x: 0, y: 0 }

scrolling:
  history: 0

font:
  normal: { family: FiraCode Nerd Font }
  size: 9.0
  use_thin_strokes: true

bell:
  duration: 0


draw_bold_text_with_bright_colors: false

# yamllint disable rule:colons
schemes:
  base16_solarized_light: &base16_solarized_light
    primary:
      background: '0xfdf6e3'
      foreground: '0x586e75'
    cursor:
      text: '0xfdf6e3'
      cursor: '0x586e75'
    normal:
      black:   '0xfdf6e3'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0x586e75'
    bright:
      black:   '0x839496'
      red:     '0xcb4b16'
      green:   '0xeee8d5'
      yellow:  '0x93a1a1'
      blue:    '0x657b83'
      magenta: '0x073642'
      cyan:    '0x6c71c4'
      white:   '0x002b36'

  base16_solarized_dark: &base16_solarized_dark
    primary:
      background: '0x002b36'
      foreground: '0x93a1a1'
    cursor:
      text: '0x002b36'
      cursor: '0x93a1a1'
    normal:
      black:   '0x002b36'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0x93a1a1'
    bright:
      black:   '0x657b83'
      red:     '0xcb4b16'
      green:   '0x073642'
      yellow:  '0x586e75'
      blue:    '0x839496'
      magenta: '0xeee8d5'
      cyan:    '0x6c71c4'
      white:   '0xfdf6e3'
# yamllint enable rule:colons

colors: *base16_solarized_light

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
  url:
    launcher: open
    modifiers: Command

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

live_config_reload: true

shell:
  program: zsh
  args:
  - --login
  - -c
  - tmux-session master
