window:
  padding: { x: 0, y: 0 }

scrolling:
  history: 0

font:
  normal: { family: FiraCode Nerd Font }
  size: 9.0
  use_thin_strokes: true

bell:
  duration: 0


draw_bold_text_with_bright_colors: false

# yamllint disable rule:colons
schemes:
  solarized_light: &solarized_light
    primary:
      background: '#fdf6e3'
      foreground: '#657b83'
    cursor:
      text:   '#fdf6e3'
      cursor: '#657b83'
    normal:
      black:   '#eee8d5'
      red:     '#dc322f'
      green:   '#859900'
      yellow:  '#b58900'
      blue:    '#268bd2'
      magenta: '#d33682'
      cyan:    '#2aa198'
      white:   '#073642'
    bright:
      black:   '#fdf6e3'
      red:     '#cb4b16'
      green:   '#586e75'
      yellow:  '#657b83'
      blue:    '#839496'
      magenta: '#6c71c4'
      cyan:    '#93a1a1'
      white:   '#002b36'

  solarized_dark: &solarized_dark
    primary:
      background: '#002b36'
      foreground: '#839496'
    cursor:
      text:   '#002b36'
      cursor: '#839496'
    normal:
      black:   '#073642'
      red:     '#dc322f'
      green:   '#859900'
      yellow:  '#b58900'
      blue:    '#268bd2'
      magenta: '#d33682'
      cyan:    '#2aa198'
      white:   '#eee8d5'
    bright:
      black:   '#002b36'
      red:     '#cb4b16'
      green:   '#93a1a1'
      yellow:  '#839496'
      blue:    '#657b83'
      magenta: '#6c71c4'
      cyan:    '#586e75'
      white:   '#fdf6e3'

  base16_solarized_light: &base16_solarized_light
    primary:
      background: '0xfdf6e3'
      foreground: '0x586e75'
    cursor:
      text: '0xfdf6e3'
      cursor: '0x586e75'
    normal:
      black:   '0xfdf6e3'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0x6c71c4'
      cyan:    '0x2aa198'
      white:   '0x586e75'
    bright:
      black:   '0x839496'
      red:     '0xcb4b16'
      green:   '0xeee8d5'
      yellow:  '0x93a1a1'
      blue:    '0x657b83'
      magenta: '0x073642'
      cyan:    '0xd33682'
      white:   '0x002b36'

  base16_solarized_dark: &base16_solarized_dark
    primary:
      background: '0x002b36'
      foreground: '0x93a1a1'
    cursor:
      text: '0x002b36'
      cursor: '0x93a1a1'
    normal:
      black:   '0x002b36'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0x6c71c4'
      cyan:    '0x2aa198'
      white:   '0x93a1a1'
    bright:
      black:   '0x657b83'
      red:     '0xcb4b16'
      green:   '0x073642'
      yellow:  '0x586e75'
      blue:    '0x839496'
      magenta: '0xeee8d5'
      cyan:    '0xd33682'
      white:   '0xfdf6e3'

  ayu_dark: &ayu_dark
    primary:
      background: '#0A0E14'
      foreground: '#B3B1AD'
    normal:
      black:   '#01060E'
      red:     '#EA6C73'
      green:   '#91B362'
      yellow:  '#F9AF4F'
      blue:    '#53BDFA'
      magenta: '#FAE994'
      cyan:    '#90E1C6'
      white:   '#C7C7C7'
    bright:
      black:   '#686868'
      red:     '#F07178'
      green:   '#C2D94C'
      yellow:  '#FFB454'
      blue:    '#59C2FF'
      magenta: '#FFEE99'
      cyan:    '#95E6CB'
      white:   '#FFFFFF'
# yamllint enable rule:colons

colors: *solarized_light

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
  url:
    launcher: open
    modifiers: Command

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

live_config_reload: true

shell:
  program: zsh
  args:
  - --login
  - -c
  - tmux-session master
