window:
  padding: { x: 0, y: 0 }
  startup_mode: 'Maximized'

scrolling:
  history: 0

font:
  normal: { family: Fira Code }
  bold: { family: Fira Code }
  italic: { family: Fira Code }
  size: 7.0
  use_thin_strokes: true

visual_bell:
  duration: 0


# yamllint disable rule:colons
draw_bold_text_with_bright_colors: false
colors:
  primary:
    background: '0x002b36'
    foreground: '0x839496'

  cursor:
    text: '0x000000'
    cursor: '0xffffff'

  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xc397d8'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'

  dim:
    black:   '0x333333'
    red:     '0xf2777a'
    green:   '0x99cc99'
    yellow:  '0xffcc66'
    blue:    '0x6699cc'
    magenta: '0xcc99cc'
    cyan:    '0x66cccc'
    white:   '0xdddddd'
# yamllint enable rule:colons

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
  url:
    launcher: open
    modifiers: Command

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

live_config_reload: true

shell:
  program: zsh
  args:
  - --login
  - -c
  - tmux-session master

key_bindings:
- { key: F1, chars: "\x1bop" }
- { key: F2, chars: "\x1boq" }
- { key: F3, chars: "\x1bor" }
- { key: F4, chars: "\x1bos" }
- { key: F5, chars: "\x1b[15~" }
- { key: F6, chars: "\x1b[17~" }
- { key: F7, chars: "\x1b[18~" }
- { key: F8, chars: "\x1b[19~" }
- { key: F9, chars: "\x1b[20~" }
- { key: F10, chars: "\x1b[21~" }
- { key: F11, chars: "\x1b[23~" }
- { key: F12, chars: "\x1b[24~" }
