summary = true
wrap = false
reverse = false

export_locations = true

default_job = "clippy"

[keybindings]
r = "toggle-raw-output"
shift-r = "rerun"
g = "scroll-to-top"
shift-g = "scroll-to-bottom"
k = "scroll-lines(-1)"
j = "scroll-lines(1)"

[jobs.check]
command = [
  "cargo", "rubber",
  "check",
  "--workspace",
  "--all-targets",
  "--all-features",
  "--color", "always",
]

[jobs.clippy]
command = [
  "cargo", "rubber",
  "clippy",
  "--workspace",
  "--all-targets",
  "--all-features",
  "--color", "always",
]

[jobs.deny]
command = [
  "cargo",
  "deny",
  "--workspace",
  "--all-features",
  "--locked",
  "check",
  "--allow", "duplicate",
]
need_stdout = true

[jobs.doc]
command = [
  "cargo", "rubber",
  "doc",
  "--no-deps",
  "--color", "always",
]

[jobs.test]
command = [
  "cargo", "rubber",
  "test",
  "--workspace",
  "--all-features",
  "--color", "always",
  "--",
  "--color", "always",
]
need_stdout = true
