directory: ~/Music/Library
library: ~/Music/Library/.beets.db

plugins: random bpd replaygain fetchart

import:
  move: true

replaygain:
  backend: gstreamer

fetchart:
  sources: [filesystem, coverart]
