format = """
$username[@](green dimmed)$hostname $directory$git_branch$git_commit$git_state$git_status$all
$jobs$battery$time($status )$cmd_duration$character
"""

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[character]
success_symbol = "→"
error_symbol = "[→](red)"
vicmd_symbol = "[↓](yellow)"

[cmd_duration]
style = "purple"

[directory]
style = "purple"
truncate_to_repo = false

[conda]
symbol = " "

[dotnet]
style = "blue"
symbol = " "

[git_branch]
style = "yellow"
symbol = " "

[git_commit]
style = "green"

[git_status]
style = "red dimmed"

[golang]
style = "cyan"
symbol = " "

[hg_branch]
symbol = " "

[hostname]
format = "[$hostname]($style)"
style = "green"
ssh_only = false

[java]
symbol = " "

[line_break]
disabled = true

[memory_usage]
symbol = " "

[nodejs]
style = "green"
symbol = " "

[package]
style = "orange"
symbol = " "

[php]
style = "red"
symbol = " "

[python]
style = "yellow"
symbol = " "

[ruby]
style = "red"
symbol = " "

[rust]
style = "red"
symbol = " "

[status]
disabled = false
symbol                = "✖ "
success_symbol        = "✔️"
not_executable_symbol = "🚫 "
not_found_symbol      = "🔍"
sigint_symbol         = "🧱 "
signal_symbol         = "⚡"
format = "[$symbol($common_meaning)(SIG$signal_name)($maybe_int)]($style)"
pipestatus_separator = " | "
pipestatus_format = "\\[ $pipestatus \\] → [$symbol($common_meaning)(SIG$signal_name)($maybe_int)]($style)"
map_symbol = true
pipestatus = true

[time]
disabled = false
format = "[$time]($style) "
style = "yellow dimmed"
time_format = "%H:%M"

[username]
format = "[$user]($style)"
style_user = "green"
show_always = true
